"""
Convert a tsv of an affinity matrix to a serialized numpy matrix.

This is designed to convert affinity matrices generated by ReSearcher.cc to
numpy matrices so that we can experiment with them.
"""
import argparse
import numpy as np

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Convert tsv sparse affinity matrix to serialized numpy.')
    parser.add_argument('filename', type=str,
                        help='the name of the file to convert.')
    parser.add_argument('outfile', type=str,
                        help='where to write the output.')
    args = parser.parse_args()

    with open(args.filename, 'r') as f:
        rev_count = 0
        pap_count = 0
        rev_to_idx = {}
        pap_to_idx = {}
        aff_mat = []
        for line in f:
            splits = line.split('\t')
            rev, pap, score = splits[0], splits[1], splits[2]
            if rev not in rev_to_idx:
                rev_to_idx[rev] = rev_count
                rev_count += 1
            if pap not in pap_to_idx:
                pap_to_idx[pap] = pap_count
                pap_count += 1
            ridx = rev_to_idx[rev]
            pidx = pap_to_idx[pap]
            if len(aff_mat) <= ridx:
                aff_mat.append([])
            while len(aff_mat[ridx]) <= pidx:
                aff_mat[ridx].append(0.0)
            aff_mat[ridx][pidx] = score
        np.save(args.outfile, np.array(aff_mat, dtype=float))
